/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CloseAccountDialog extends javax.swing.JDialog {

    /**
     * Creates new form CloseAccountDialog
     * @param parent
     * @param modal
     */
    public CloseAccountDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       setLocation(70,70);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountInfoTable = new javax.swing.JTable();
        closeAcctBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PCCS-Close Account");
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());

        accountInfoTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        accountInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Name", null},
                {"Account No", null},
                {"Designation", null},
                {"Batch No", null},
                {"Share Amount", null},
                {"Share Interest", null},
                {"RD Amt", null},
                {"RD Interest", null},
                {"Unpaid Loan Amount", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accountInfoTable.setRowHeight(20);

        closeAcctBt.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        closeAcctBt.setForeground(new java.awt.Color(255, 0, 0));
        closeAcctBt.setText("Close Account");
        closeAcctBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAcctBtActionPerformed(evt);
            }
        });

        jLabel1.setText("Click here to close account !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountInfoTable, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(closeAcctBt)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accountInfoTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeAcctBt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        if (accountInfoTable.getColumnModel().getColumnCount() > 0) {
            accountInfoTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            accountInfoTable.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAcctBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAcctBtActionPerformed
        // TODO add your handling code here
     int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to Close the Account ?","PCCS-Close Account",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
             if(CONFIRMATION_CHECK==0)
             {
                 try{
                 int account_no=Integer.parseInt(""+accountInfoTable.getValueAt(1,1));
                 
                 PreparedStatement pstm_update;
        pstm_update=LoginPage.homepage.con.prepareStatement("update customer set account_status=? where account_no=?");
        pstm_update.setInt(2,account_no);
        pstm_update.setBoolean(1,false);
      pstm_update.executeUpdate();  
            JOptionPane.showMessageDialog(this,"Account is Closed succesfully !","PCCS-Close Account",JOptionPane.INFORMATION_MESSAGE);
                closeAcctBt.setEnabled(false);
                this.dispose();
                LoginPage.homepage.acList.getAccountList();
             }
             catch(NumberFormatException | SQLException e)
             {
              JOptionPane.showMessageDialog(this,"Error !","PCCS-ERROR",JOptionPane.ERROR_MESSAGE);
  
             }
             }
                     
    }//GEN-LAST:event_closeAcctBtActionPerformed
public  void setAccountInfo(int account_no)
{ 
    ResultSet rs;
    String name,batch_no,designation;
    int share_amt,share_int,rd_amt,rd_int,unpaid_loan;
  
    Connection con=LoginPage.homepage.con;
        try{
  PreparedStatement pstm=con.prepareStatement("select name,designation,batch_no,share_bal,share_interest,rdbal,rd_interest,unpaid_loan_amount from customer where account_no=? ");
       pstm.setInt(1,account_no);
          rs=pstm.executeQuery();
            
         if(rs.next())
        {
               name=rs.getString(1);
               designation=rs.getString(2);
               batch_no=rs.getString(3);
               share_amt=rs.getInt(4);
               share_int=rs.getInt(5);
               rd_amt=rs.getInt(6);
               rd_int=rs.getInt(7);
               unpaid_loan=rs.getInt(8);
               accountInfoTable.setValueAt(name,0,1);
               accountInfoTable.setValueAt(account_no,1,1);
               accountInfoTable.setValueAt(designation,2,1);
               accountInfoTable.setValueAt(batch_no,3,1);
               accountInfoTable.setValueAt(share_amt,4,1);
               accountInfoTable.setValueAt(share_int,5,1);
               accountInfoTable.setValueAt(rd_amt,6,1);
               accountInfoTable.setValueAt(rd_int,7,1);
               accountInfoTable.setValueAt(unpaid_loan,8,1);
             if(share_amt!=0| share_int!=0 | rd_amt!=0 | rd_int!=0 | unpaid_loan!=0)
             {
                closeAcctBt.setEnabled(false);
             }
                        
             }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error !","PCCS-ERROR",JOptionPane.ERROR_MESSAGE);
        }  
    
}
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountInfoTable;
    private javax.swing.JButton closeAcctBt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
