/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class LoanSanction extends javax.swing.JDialog {
Adminpage refAdminpageLS=LoginPage.homepage;
LoanManage refLoanManage=refAdminpageLS.loanmanage;  
     int customer_unpaid_loan_amount;
     int customer_paid_interest_amount;
     int LOAN_AMOUNT,CUR_LOAN_AMOUNT;
     int LOAN_INSTALLMENT_AMT,LOAN_INTEREST_AMT;
      short NO_OF_INSTALLMENTS;
      
      
    /**
     * Creates new form RDInterestDep
     * @param parent
     * @param modal
     */
    public LoanSanction(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/6,size.height/8);   
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        acctnoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lsaTF = new javax.swing.JTextField();
        noiTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        calculateBt = new javax.swing.JButton();
        getLoanBt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        insamtTF = new javax.swing.JTextField();
        intamtTF = new javax.swing.JTextField();
        depositloanBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loan Sanction");
        setIconImage(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Account No :");

        acctnoTF.setEditable(false);
        acctnoTF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        acctnoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name          :");

        nameTF.setEditable(false);
        nameTF.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Loan Sanction Amount");

        lsaTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lsaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        noiTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        noiTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("No of Installments");

        calculateBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculateBt.setForeground(new java.awt.Color(0, 51, 51));
        calculateBt.setText("Calculate");
        calculateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtActionPerformed(evt);
            }
        });

        getLoanBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getLoanBt.setForeground(new java.awt.Color(153, 0, 0));
        getLoanBt.setText("Get Loan");
        getLoanBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getLoanBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Installment Amt");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Interest Amt");

        insamtTF.setEditable(false);
        insamtTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        insamtTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        intamtTF.setEditable(false);
        intamtTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        intamtTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        depositloanBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositloanBt.setForeground(new java.awt.Color(0, 153, 51));
        depositloanBt.setText("Deposit Amt");
        depositloanBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositloanBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lsaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(getLoanBt)
                                .addComponent(noiTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(calculateBt)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insamtTF)
                            .addComponent(intamtTF, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depositloanBt)
                        .addGap(90, 90, 90))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lsaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(insamtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(intamtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getLoanBt)
                    .addComponent(calculateBt)
                    .addComponent(depositloanBt))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(acctnoTF)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtActionPerformed
        // TODO add your handling code here:
        try
         { 
         String CLA=lsaTF.getText().trim();
         String NOI=noiTF.getText().trim();
         CUR_LOAN_AMOUNT=Integer.parseInt(CLA);
      NO_OF_INSTALLMENTS=Short.parseShort(NOI);
      if(CUR_LOAN_AMOUNT>0 && NO_OF_INSTALLMENTS>0)
      {
         if(!CLA.equals("") && !NOI.equals(""))
         {
     
            
            int account_no=Integer.parseInt(acctnoTF.getText().trim());
          PreparedStatement   pstls=refAdminpageLS.con.prepareStatement("select"
                  + " unpaid_loan_amount,paid_interest_amount from customer where account_no=?");
            pstls.setInt(1, account_no);
         ResultSet rs=pstls.executeQuery();
         if(rs.next())
         { 
             customer_unpaid_loan_amount=rs.getInt(1);
             customer_paid_interest_amount=rs.getInt(2);
         }
        
    
      
         if(customer_unpaid_loan_amount==0)
          {
              LOAN_AMOUNT=CUR_LOAN_AMOUNT;
          }
          else
          {
          LOAN_AMOUNT=CUR_LOAN_AMOUNT+customer_unpaid_loan_amount;
         }
         LOAN_INSTALLMENT_AMT=LOAN_AMOUNT/NO_OF_INSTALLMENTS;
         short LOAN_INTEREST_PER=refAdminpageLS.LOAN_INT;
         LOAN_INTEREST_AMT=(int)(((double)((LOAN_AMOUNT+LOAN_INSTALLMENT_AMT)*(LOAN_INTEREST_PER))/100)*((double)NO_OF_INSTALLMENTS/2))/NO_OF_INSTALLMENTS;
         insamtTF.setText(""+LOAN_INSTALLMENT_AMT);
         intamtTF.setText(""+LOAN_INTEREST_AMT);
         getLoanBt.setEnabled(true);

         }
         else
         {
                JOptionPane.showMessageDialog(this,"<html><body><B>FILL THE FIELDS</b></body></html>","PCCS-Loan Calculate",JOptionPane.WARNING_MESSAGE);
         }
      } }
catch(  NumberFormatException | SQLException | HeadlessException e )
{
       JOptionPane.showMessageDialog(this,"<html><body><B>    Error !</b></body></html>","PCCS-Loan Calculate",JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_calculateBtActionPerformed

    private void getLoanBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getLoanBtActionPerformed
        // TODO add your handling code here:{
        getLoanBt.setEnabled(false);
         int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"<html><body><B>Are yoy sure you want to sanction the loan ?</b></body></html>","PCCS-Loan Sanction",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
        try{
              int account_no=Integer.parseInt(acctnoTF.getText().trim());
              String  loan_date=LoginPage.homepage.TransactionDateFTF.getText().trim();
                    //get the current date
              
       PreparedStatement      pstls=refAdminpageLS.con.prepareStatement("insert into loan_payment(particulars,account_no,"
                + "withdraw_loan_amount,remaining_loan_amount) values(?,?,?,?)");
        
        pstls.setString(1,loan_date);
        pstls.setInt(2,account_no);
        pstls.setInt(3,CUR_LOAN_AMOUNT);
        pstls.setInt(4,LOAN_AMOUNT);
        pstls.executeUpdate(); 
        pstls.close();
        
            pstls=refAdminpageLS.con.prepareStatement("insert into "
                  + "loan_sanction values(?,?,?,?,?,?,?)");
           pstls.setString(1,loan_date);
           pstls.setInt(2,account_no);
           pstls.setInt(3,CUR_LOAN_AMOUNT);
          pstls.setShort(4,NO_OF_INSTALLMENTS);
          pstls.setInt(5,LOAN_INSTALLMENT_AMT);
          pstls.setInt(6,LOAN_INTEREST_AMT);
          pstls.setInt(7,customer_unpaid_loan_amount);
          pstls.executeUpdate();  
          pstls.close();
          
            pstls=refAdminpageLS.con.prepareStatement("update customer set unpaid_loan_amount=?,loan_installment_amount=?,loan_interest_amount=? where account_no=?");
            pstls.setInt(1,LOAN_AMOUNT);
            pstls.setInt(2,LOAN_INSTALLMENT_AMT);
            pstls.setInt(3,LOAN_INTEREST_AMT);
            pstls.setInt(4,account_no);
              pstls.executeUpdate(); 
              pstls.close();
              
         
          
            pstls=refAdminpageLS.con.prepareStatement("select unpaid_loan_amount,loan_installment_amount,loan_interest_amount from customer where account_no=?");
            pstls.setInt(1, account_no);
            ResultSet rs=pstls.executeQuery();
         if(rs.next())
         {
            customer_unpaid_loan_amount=rs.getInt(1);
            LOAN_INSTALLMENT_AMT=rs.getInt(2);
            LOAN_INTEREST_AMT=rs.getInt(3);
              JOptionPane.showMessageDialog(this,"<html><body><B>Loan sanctioned successfully !</b></body><html>","PCCS-Loan Sanction",JOptionPane.INFORMATION_MESSAGE);
               pstls.close();
             rs.close();
           
             getLoanBt.setEnabled(true);
             refLoanManage.InstallmentTable.setValueAt(customer_unpaid_loan_amount,4,1);
            refLoanManage.InstallmentTable.setValueAt(LOAN_INSTALLMENT_AMT,0,1);
             refLoanManage.InstallmentTable.setValueAt(LOAN_INTEREST_AMT,1,1);
             refLoanManage.InstallmentTable.setValueAt((LOAN_INSTALLMENT_AMT+LOAN_INTEREST_AMT),2,1);
            
         }
          
        }
           catch(NumberFormatException | SQLException | HeadlessException e) 
           {
              JOptionPane.showMessageDialog(this,"<html><body><B>ERROR DATABASE !</b></body></html>"+e,"PCCS-Loan Sanction",JOptionPane.ERROR_MESSAGE);  
              getLoanBt.setEnabled(true);
           }
        }
    }//GEN-LAST:event_getLoanBtActionPerformed

    private void depositloanBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositloanBtActionPerformed
        // TODO add your handling code here:
         int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"<html><body><B>Are you sure you want to deposit the Loan Installment?</b></body></html>","PCCS-Loan Deposit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
           try
        {
       int account_no=Integer.parseInt(acctnoTF.getText().trim());
          PreparedStatement   pstld=refAdminpageLS.con.prepareStatement("select"
                  + " unpaid_loan_amount,paid_interest_amount from customer where account_no=?");
            pstld.setInt(1, account_no);
         ResultSet rs=pstld.executeQuery();
         if(rs.next())
         { 
             customer_unpaid_loan_amount=rs.getInt(1);
             customer_paid_interest_amount=rs.getInt(2);
         }
      rs.close();
      pstld.close();
              String  loan_date=LoginPage.homepage.TransactionDateFTF.getText().trim();
        
    int  INSTALLMENT_PAID=Integer.parseInt(insamtTF.getText().trim());
    int  INTEREST_PAID= Integer.parseInt(intamtTF.getText().trim());
       
        int  TOTAL_INT_PAID;
        int REM_UNPAID_LOAN_AMOUNT=customer_unpaid_loan_amount-INSTALLMENT_PAID;
       
        TOTAL_INT_PAID=customer_paid_interest_amount+INTEREST_PAID;
        pstld=refAdminpageLS.con.prepareStatement("insert into loan_payment(particulars,account_no,"
                + "installment_paid,remaining_loan_amount,interest_paid,total_interest_paid) values(?,?,?,?,?,?)");
     
        pstld.setString(1, loan_date);
        pstld.setInt(2,account_no);
         pstld.setInt(3,INSTALLMENT_PAID);
        pstld.setInt(4,REM_UNPAID_LOAN_AMOUNT);
        pstld.setInt(5,INTEREST_PAID );
        pstld.setInt(6,TOTAL_INT_PAID);
        pstld.executeUpdate();
        pstld.close();
         if(REM_UNPAID_LOAN_AMOUNT>0)
        {
        pstld=refAdminpageLS.con.prepareStatement("update customer set unpaid_loan_amount=?,paid_interest_amount=? where account_no=?");
           
            pstld.setInt(1,REM_UNPAID_LOAN_AMOUNT);
             pstld.setInt(2,TOTAL_INT_PAID);
            pstld.setInt(3, account_no);
             pstld.executeUpdate();
             pstld.close();
     JOptionPane.showMessageDialog(this,"<html><body><B>Installment succesfully Deposited!</b></body></html>","PCCS-Loan Deposit",JOptionPane.INFORMATION_MESSAGE);
      refLoanManage.InstallmentTable.setValueAt(REM_UNPAID_LOAN_AMOUNT,4,1);
              
                    }  
          if(REM_UNPAID_LOAN_AMOUNT==0)
        {
           pstld=refAdminpageLS.con.prepareStatement("update customer set unpaid_loan_amount=?,"
                + "loan_installment_amount=?,loan_interest_amount=?,paid_interest_amount=? where account_no=?");
           
             pstld.setInt(1,0);
              pstld.setInt(2,0);
               pstld.setInt(3,0);
             pstld.setInt(4,0);
            pstld.setInt(5, account_no);
             pstld.executeUpdate();
             pstld.close();
     JOptionPane.showMessageDialog(this,"<html><body><B>Installment succesfully Deposited !</b></body></html>","PCCS-Loan Deposit",JOptionPane.INFORMATION_MESSAGE);
      refLoanManage.InstallmentTable.setValueAt(0,0,1);
        refLoanManage.InstallmentTable.setValueAt(0,1,1);
          refLoanManage.InstallmentTable.setValueAt(0,2,1);
            refLoanManage.InstallmentTable.setValueAt(0,4,1);
              
        }
            }
           catch(NumberFormatException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this,"<html><body><B>ERROR DATABASE !</b></body></html>","PCCS-Loan Deposit",JOptionPane.ERROR_MESSAGE);
           
        }
        }
    }//GEN-LAST:event_depositloanBtActionPerformed

  
   



    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField acctnoTF;
    javax.swing.JButton calculateBt;
    javax.swing.JButton depositloanBt;
    javax.swing.JButton getLoanBt;
    javax.swing.JTextField insamtTF;
    javax.swing.JTextField intamtTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    javax.swing.JTextField lsaTF;
    javax.swing.JTextField nameTF;
    javax.swing.JTextField noiTF;
    // End of variables declaration//GEN-END:variables
}
