/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;



import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LoanManage extends javax.swing.JPanel {
    Adminpage refAdminpageLoan=LoginPage.homepage;
  
    
    public LoanManage() {
        initComponents();
       }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        acctnoTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        designationTF = new javax.swing.JTextField();
        batchnoTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InstallmentTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        loandepositBt = new javax.swing.JButton();
        loanSanctionBt = new javax.swing.JButton();
        HOLSBt = new javax.swing.JButton();

        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(702, 337));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Account No   ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Name            ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Designation  ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Batch No       ");

        acctnoTF.setEditable(false);
        acctnoTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        acctnoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nameTF.setEditable(false);
        nameTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        designationTF.setEditable(false);
        designationTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        designationTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        batchnoTF.setEditable(false);
        batchnoTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batchnoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(designationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(batchnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        InstallmentTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InstallmentTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        InstallmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Installment Amount", null},
                {"Installment Interest", null},
                {"Total Amount", null},
                {null, null},
                {"Unpaid Loan", null}
            },
            new String [] {
                "<html><body><b>Amount Type</b></body></html>", "<html><body><b>Amount</b></body></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InstallmentTable.setRowHeight(30);
        jScrollPane1.setViewportView(InstallmentTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        loandepositBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loandepositBt.setText("Loan Deposit");
        loandepositBt.setFocusable(false);
        loandepositBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loandepositBtActionPerformed(evt);
            }
        });
        jPanel2.add(loandepositBt);

        loanSanctionBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loanSanctionBt.setText("Loan Sanction");
        loanSanctionBt.setFocusable(false);
        loanSanctionBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanSanctionBtActionPerformed(evt);
            }
        });
        jPanel2.add(loanSanctionBt);

        HOLSBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HOLSBt.setText("Loan History");
        HOLSBt.setToolTipText("Click here for loan sanction history");
        HOLSBt.setFocusable(false);
        HOLSBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOLSBtActionPerformed(evt);
            }
        });
        jPanel2.add(HOLSBt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void loanSanctionBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanSanctionBtActionPerformed
        int account_no=refAdminpageLoan.account_noForLoanAManage;
         LoanSanction LSWindow=new LoanSanction(refAdminpageLoan, true);
          LSWindow.acctnoTF.setText(""+account_no);
          LSWindow.nameTF.setText(nameTF.getText().trim());
          LSWindow.depositloanBt.setEnabled(false);
          LSWindow.getLoanBt.setEnabled(false);
          LSWindow.setVisible(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_loanSanctionBtActionPerformed

    private void loandepositBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loandepositBtActionPerformed
           
           int UNPAID_LOAN_AMT=Integer.parseInt(""+InstallmentTable.getValueAt(4,1));
           if(UNPAID_LOAN_AMT>0)
           {
               int INS_AMT=Integer.parseInt(""+InstallmentTable.getValueAt(0,1));
           int INT_AMT=Integer.parseInt(""+InstallmentTable.getValueAt(1,1));
        int account_no=refAdminpageLoan.account_noForLoanAManage;
          LoanSanction LDWindow=new LoanSanction(refAdminpageLoan, true);
          LDWindow.acctnoTF.setText(""+account_no);
          LDWindow.nameTF.setText(nameTF.getText());
          LDWindow.calculateBt.setEnabled(false);
          LDWindow.getLoanBt.setEnabled(false);
          LDWindow.noiTF.setEditable(false);
          LDWindow.lsaTF.setEditable(false);
          LDWindow.insamtTF.setText(""+INS_AMT);
           LDWindow.intamtTF.setText(""+INT_AMT);
          LDWindow.setVisible(true);
           }
           else
           {
                  JOptionPane.showMessageDialog(null,"<html><body><b>Loan Status=UNACTIVE !</B></body></html>","PCCS-Loan Deposit",JOptionPane.INFORMATION_MESSAGE);
           }
    

// TODO add your handling code here:
    }//GEN-LAST:event_loandepositBtActionPerformed

    private void HOLSBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOLSBtActionPerformed
     try
     {    ResultSet rsloan;
         HistoryOfLoanSanction his;
           int account_no=refAdminpageLoan.account_noForLoanAManage;
         his=new HistoryOfLoanSanction(refAdminpageLoan, true,account_no);
         his.acctnoTF.setText(""+account_no);
         his.nameTF.setText(nameTF.getText());
     PreparedStatement   pstlh=refAdminpageLoan.con.prepareStatement("select * from loan_sanction where account_no=? order by loan_sanction_date asc");
          pstlh.setInt(1, account_no);
          rsloan=pstlh.executeQuery();
          String HisParticulars;
          
          int loan_amount,Installment_amount,interest_amount,previous_unpaid_amount;
          short no_of_installments;
        DefaultTableModel tmHis=(DefaultTableModel)his.HistoryTable.getModel();
              while(true)
              {
                  int c=tmHis.getRowCount();
                  if(c==0)
                      break;
                  else
                      tmHis.removeRow(0);
              }  
              
        while(rsloan.next())
        {
          HisParticulars=rsloan.getString(1);
           loan_amount =rsloan.getInt(3);
            Installment_amount=rsloan.getInt(5);
           interest_amount =rsloan.getInt(6);
          previous_unpaid_amount =rsloan.getInt(7);
           no_of_installments=rsloan.getShort(4);
               Object tb[]={HisParticulars,loan_amount,no_of_installments,Installment_amount,interest_amount,previous_unpaid_amount};
                tmHis.addRow(tb);
            
        }
        his.setVisible(true);
        rsloan.close();
        pstlh.close();
        
     }
     
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"<html><body><B>Error related to database !</b></body></html>","PCCS-Loan History",JOptionPane.INFORMATION_MESSAGE);
}
     
// TODO add your handling code here:
    }//GEN-LAST:event_HOLSBtActionPerformed
public void getLoanInfo() throws SQLException
{
   Connection conloan=refAdminpageLoan.con;//initialize the connection with database pccs;
     int account_no=refAdminpageLoan.account_noForLoanAManage;
  PreparedStatement  pstloan=conloan.prepareStatement("select name,designation,batch_no,unpaid_loan_amount,paid_interest_amount,loan_installment_amount,loan_interest_amount from customer where account_no=?");
    pstloan.setInt(1, account_no);
    int loanInstallment_amount,loanInterest_amount;
    int customer_unpaid_loan_amount,customer_paid_interest_amount;
       ResultSet rs=pstloan.executeQuery();
         if(rs.next())
         {
             acctnoTF.setText(""+account_no);
             nameTF.setText(rs.getString(1));
             designationTF.setText(rs.getString(2));
             batchnoTF.setText(rs.getString(3));
             customer_unpaid_loan_amount=rs.getInt(4);
             customer_paid_interest_amount=rs.getInt(5);
             loanInstallment_amount=rs.getInt(6);
             loanInterest_amount=rs.getInt(7);
             InstallmentTable.setValueAt(customer_unpaid_loan_amount,4,1);
             InstallmentTable.setValueAt(loanInstallment_amount,0,1);
             InstallmentTable.setValueAt( loanInterest_amount,1,1);
             InstallmentTable.setValueAt(loanInstallment_amount+loanInterest_amount,2,1);
           }
         
        pstloan.close();
        rs.close();
      
    
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HOLSBt;
    javax.swing.JTable InstallmentTable;
    private javax.swing.JTextField acctnoTF;
    private javax.swing.JTextField batchnoTF;
    private javax.swing.JTextField designationTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loanSanctionBt;
    private javax.swing.JButton loandepositBt;
    private javax.swing.JTextField nameTF;
    // End of variables declaration//GEN-END:variables
}
