/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PCCS;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class LoginPage extends javax.swing.JFrame {
static Adminpage homepage;
static LoginPage loginForm;
String username,password;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
         Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/6,size.height/8);   
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBt = new javax.swing.JButton();
        usernameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordF = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        winMenuItem = new javax.swing.JMenuItem();
        metalMenuItem = new javax.swing.JMenuItem();
        nimbusMenuItem = new javax.swing.JMenuItem();
        changeUPmenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCCS -Login Window");
        setAlwaysOnTop(true);
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());
        setResizable(false);

        loginBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginBt.setForeground(new java.awt.Color(0, 102, 51));
        loginBt.setText("Login");
        loginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtActionPerformed(evt);
            }
        });

        usernameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTF.setText("sheelu");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Password");

        passwordF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordF.setText("sheelu");

        jMenu2.setText("Settings");

        jMenu1.setText("Look and Feel");

        winMenuItem.setText("Window");
        winMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(winMenuItem);

        metalMenuItem.setText("Metal");
        metalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metalMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(metalMenuItem);

        nimbusMenuItem.setText("Nimbus");
        nimbusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimbusMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(nimbusMenuItem);

        jMenu2.add(jMenu1);

        changeUPmenuItem.setText("Change Username/Password");
        changeUPmenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUPmenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(changeUPmenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(loginBt)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtActionPerformed
        // TODO add your handling code here:
       loginForm.setCursor(new Cursor(Cursor.WAIT_CURSOR));
       loginForm.setEnabled(false);
        username=usernameTF.getText();
        char p[]=passwordF.getPassword();
        password=String.valueOf(p);
   Connection   con=Connectivity.connectDatabase(username,password);
        if(con==null)
        {
           JOptionPane.showMessageDialog(this,"Invalid Username or Password !"
                   + "","PCCS-Login ",JOptionPane.ERROR_MESSAGE);  
          loginForm.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
           loginForm.setEnabled(true);
        }
        else{
            try{
        homepage=new Adminpage();
        homepage.con=con;
        homepage.setPCCCS_VALUES();
        homepage.setVisible(true);
        loginForm.dispose();
        loginForm.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        loginForm.setEnabled(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error related to Database !","PCCS-Login",JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
         usernameTF.setText("");
        passwordF.setText("");
    }//GEN-LAST:event_loginBtActionPerformed

    private void winMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winMenuItemActionPerformed
        // TODO add your handling code here:
         try {
            // Set System L&F
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
     
    } 
    catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       // handle exception
    }
         changeLookandFeel();
    }//GEN-LAST:event_winMenuItemActionPerformed

    private void metalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metalMenuItemActionPerformed
        // TODO add your handling code here:
        
         try {
            // Set System L&F
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
     
    } 
    catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       // handle exception
    }
         changeLookandFeel();
    }//GEN-LAST:event_metalMenuItemActionPerformed

    private void nimbusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbusMenuItemActionPerformed
        // TODO add your handling code here:
          try {
            // Set System L&F
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
     
    } 
    catch (UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException e) {
       // handle exception
    }
         changeLookandFeel();
    }//GEN-LAST:event_nimbusMenuItemActionPerformed

    private void changeUPmenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUPmenuItemActionPerformed
        // TODO add your handling code here:
           ChangeUP changeUPDialog=new ChangeUP(this,true);
        changeUPDialog.setVisible(true);
    }//GEN-LAST:event_changeUPmenuItemActionPerformed
private void changeLookandFeel()
{
    
      SwingUtilities.updateComponentTreeUI(loginForm);
       loginForm .pack();
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
          loginForm=new LoginPage();
          loginForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changeUPmenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton loginBt;
    private javax.swing.JMenuItem metalMenuItem;
    private javax.swing.JMenuItem nimbusMenuItem;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JMenuItem winMenuItem;
    // End of variables declaration//GEN-END:variables
}
