/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;


import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JSpinner;


public class OpenAccount extends javax.swing.JPanel {
   
    private final JFormattedTextField dobFTF;
   
    public OpenAccount() {
        initComponents();
           JSpinner.DateEditor editor=(JSpinner.DateEditor)dobSpinner.getEditor();
           dobFTF=editor.getTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        nameLb = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        account_noLb = new javax.swing.JLabel();
        accountnoTf = new javax.swing.JTextField();
        batchnoLb = new javax.swing.JLabel();
        batchnoTf = new javax.swing.JTextField();
        vouchernoLb = new javax.swing.JLabel();
        vouchernoTf = new javax.swing.JTextField();
        amountLb = new javax.swing.JLabel();
        amountTf = new javax.swing.JTextField();
        designationLb = new javax.swing.JLabel();
        designationTf = new javax.swing.JTextField();
        dobLb = new javax.swing.JLabel();
        addressLb = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        addressTf = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        createAccountBt = new javax.swing.JButton();
        clearBt = new javax.swing.JButton();
        SpinnerDateModel model=new SpinnerDateModel(new Date(),null,null,Calendar.DAY_OF_YEAR);
        dobSpinner = new javax.swing.JSpinner(model);

        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        nameLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        nameLb.setText(" Name             ");

        nameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTf.setToolTipText("<=20 characters");

        account_noLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        account_noLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        account_noLb.setText("Account No  ");

        accountnoTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        batchnoLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batchnoLb.setText("Batch no      ");

        batchnoTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        batchnoTf.setToolTipText("<=20 characters");

        vouchernoLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vouchernoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        vouchernoLb.setText("Voucher no  ");

        vouchernoTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vouchernoTf.setToolTipText("<=10 characters");

        amountLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        amountLb.setText("Amount        ");

        amountTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTfActionPerformed(evt);
            }
        });

        designationLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        designationLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        designationLb.setText("Designation    ");

        designationTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        designationTf.setToolTipText("<=20 characters");

        dobLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        dobLb.setText("Date Of Birth  ");

        addressLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLb.setText("Address ");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        addressTf.setColumns(20);
        addressTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTf.setLineWrap(true);
        addressTf.setRows(5);
        addressTf.setToolTipText("<=255 characters");
        jScrollPane4.setViewportView(addressTf);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.jpg"))); // NOI18N
        jLabel44.setText("  All field are necessary");

        createAccountBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createAccountBt.setText("Create Account");
        createAccountBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(createAccountBt);

        clearBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearBt.setText("Clear");
        clearBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(clearBt);

        JSpinner.DateEditor editor=new JSpinner.DateEditor(dobSpinner,"yyyy-MM-dd");
        dobSpinner.setEditor(editor);
        dobSpinner.setToolTipText("yyyy-mm-dd");
        dobSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(dobLb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addressLb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(account_noLb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLb)
                                    .addComponent(designationLb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(designationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(amountLb)
                                        .addGap(18, 18, 18)
                                        .addComponent(amountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(accountnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(batchnoLb))
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(vouchernoLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(batchnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vouchernoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(vouchernoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nameLb))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(vouchernoLb)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(account_noLb)))
                        .addGap(18, 18, 18)
                        .addComponent(designationLb))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batchnoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batchnoLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designationTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(amountLb)
                                    .addComponent(amountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dobSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressLb)
                        .addComponent(dobLb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        dobSpinner.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtActionPerformed
        // TODO add your handling code here:
           JLabel msg_lb= new JLabel();
           msg_lb.setFont(new java.awt.Font("Times New Roman", 1, 16));
           if(!nameTf.getText().equals("") && !accountnoTf.getText().equals("")
                && !vouchernoTf.getText().equals("")&& !designationTf.getText().equals("")&&
                !batchnoTf.getText().equals("")&&
                !amountTf.getText().equals(""))
        {
        int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(null,"Are you sure you want to create account ?","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
     
        CustomerTransaction depositShareObject=new CustomerTransaction();
     try 
              {
  
        int account_no;
        int amt=Integer.parseInt(amountTf.getText().trim());
        //get mice and entry_fee from value_type table
       
        int amt_share;
       
        String doac;   //date of account creation
         short entry_fee = LoginPage.homepage.ENTRY_FEE;
            short amt_mice = LoginPage.homepage.MICE;
            amt_share=amt-(amt_mice + entry_fee);
               int customerFlag,shareFlag;
            
           
            Adminpage refAdminpageOpenAccount=LoginPage.homepage;
            
                PreparedStatement pstmCustomer = refAdminpageOpenAccount.con.prepareStatement("insert into customer values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
                pstmCustomer.setString(1, nameTf.getText().trim());
                account_no=Integer.parseInt(accountnoTf.getText().trim());
                pstmCustomer.setInt(2, account_no);
                pstmCustomer.setString(3, designationTf.getText().trim());
                pstmCustomer.setString(4, batchnoTf.getText().trim());
                pstmCustomer.setString(5, vouchernoTf.getText().trim());
                pstmCustomer.setString(6, dobFTF.getText().trim());
                doac=LoginPage.homepage.TransactionDateFTF.getText().trim();
                pstmCustomer.setString(7,doac );
                pstmCustomer.setString(8, addressTf.getText().trim());
                pstmCustomer.setInt(9, (amt_share));
                pstmCustomer.setInt(10, 0);
                pstmCustomer.setInt(11, 0);
                pstmCustomer.setInt(12, 0);
                pstmCustomer.setInt(13, 0);
                pstmCustomer.setInt(14, 0);
                pstmCustomer.setInt(15, 0);
                pstmCustomer.setInt(16, 0);
                pstmCustomer.setShort(17,entry_fee);
                pstmCustomer.setShort(18,amt_mice);
                short RD_INT_YEARS=0;
                pstmCustomer.setShort(19,RD_INT_YEARS);
                boolean STATUS=true;
                pstmCustomer.setBoolean(20,STATUS);
                customerFlag=pstmCustomer.executeUpdate();
                
                shareFlag=depositShareObject.depositOrWithdraw(account_no, doac,amt_share,amt_share,"share","deposit_amount","balance");
                if(customerFlag!=0 && shareFlag!=0 )
                    
                {
                    msg_lb.setText("<html><body>"
                            + account_no+"<br>Account Created Successfully ! "+"</body></html>");
                    msg_lb.setFont(new java.awt.Font("Times New Roman", 1, 16));
                    
                    JOptionPane.showMessageDialog(null,msg_lb,"PCCS-Open Account",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    msg_lb.setText("\nYou have Entered wrong data");
                    JOptionPane.showMessageDialog(null,msg_lb
                            ,"PCCS-Open Account",JOptionPane.ERROR_MESSAGE);
                }   
        }
        catch(SQLException | NumberFormatException | HeadlessException e)
        {  msg_lb.setText("\nUnable to create account !\n   ERROR");
          JOptionPane.showMessageDialog(null,msg_lb
                    ,"PCCS-Open Account",JOptionPane.ERROR_MESSAGE);  
        }
        }
       
        }
            else
           {
             msg_lb.setText("\nFill all necessary Fields");
          JOptionPane.showMessageDialog(null,msg_lb
                    ,"PCCS-Open Account",JOptionPane.WARNING_MESSAGE);  
           }
       
    }//GEN-LAST:event_createAccountBtActionPerformed

    private void clearBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtActionPerformed

    private void amountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTfActionPerformed
public void clearFields()
{
    nameTf.setText("");
    accountnoTf.setText("");
    vouchernoTf.setText("");
    addressTf.setText("");
    batchnoTf.setText("");
    designationTf.setText("");
    amountTf.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account_noLb;
    private javax.swing.JTextField accountnoTf;
    private javax.swing.JLabel addressLb;
    private javax.swing.JTextArea addressTf;
    private javax.swing.JLabel amountLb;
    private javax.swing.JTextField amountTf;
    private javax.swing.JLabel batchnoLb;
    private javax.swing.JTextField batchnoTf;
    private javax.swing.JButton clearBt;
    private javax.swing.JButton createAccountBt;
    private javax.swing.JLabel designationLb;
    private javax.swing.JTextField designationTf;
    private javax.swing.JLabel dobLb;
    private javax.swing.JSpinner dobSpinner;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel nameLb;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel vouchernoLb;
    private javax.swing.JTextField vouchernoTf;
    // End of variables declaration//GEN-END:variables
}
