/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class RDForm extends javax.swing.JDialog {
final int MONTHLY_RD_DEPOSIT_AMOUNT=200;
  ViewAccount temp_customer=LoginPage.homepage.customer;
    /**
     * Creates new form RDInterestDep
     * @param parent
     * @param modal
     */
    public RDForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        rdTF.setText(""+MONTHLY_RD_DEPOSIT_AMOUNT);
          //set the dialog in middle of the screen
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/6,size.height/8);   
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        acctnoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        getAmtBt = new javax.swing.JButton();
        yrSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        wrdTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        withdrawRdBt = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        wiamtTF = new javax.swing.JTextField();
        yrintsp = new javax.swing.JSpinner();
        getIntAmtBt = new javax.swing.JButton();
        withdrawRDIntBt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdTF = new javax.swing.JTextField();
        depositRDBt = new javax.swing.JButton();
        rdIntTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PCCS");
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Account No :");

        acctnoTF.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name          :");

        nameTF.setEditable(false);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("RD Withdraw"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RD Balance", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        getAmtBt.setText("Get Amt");
        getAmtBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAmtBtActionPerformed(evt);
            }
        });

        yrSpinner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yrSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        yrSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yrSpinnerStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Years");

        wrdTF.setEditable(false);
        wrdTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        wrdTF.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("RD Amt");

        withdrawRdBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        withdrawRdBt.setForeground(new java.awt.Color(255, 0, 0));
        withdrawRdBt.setText("Withdraw");
        withdrawRdBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawRdBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getAmtBt)
                .addGap(18, 18, 18))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wrdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(withdrawRdBt))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(yrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAmtBt)
                    .addComponent(yrSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(withdrawRdBt)
                .addContainerGap())
        );

        jPanel5.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RD Interest", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("RD Interest Amt");

        yrintsp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yrintsp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        getIntAmtBt.setText("Get Int Amt");
        getIntAmtBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getIntAmtBtActionPerformed(evt);
            }
        });

        withdrawRDIntBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        withdrawRDIntBt.setForeground(new java.awt.Color(204, 0, 0));
        withdrawRDIntBt.setText("Withdraw Int");
        withdrawRDIntBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawRDIntBtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Years");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawRDIntBt)
                .addGap(41, 41, 41))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(yrintsp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getIntAmtBt))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(wiamtTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yrintsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getIntAmtBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wiamtTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(withdrawRDIntBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel7);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RD Deposit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Monthly Amount");

        rdTF.setEditable(false);
        rdTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        depositRDBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        depositRDBt.setForeground(new java.awt.Color(0, 204, 0));
        depositRDBt.setText("Deposit");
        depositRDBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositRDBtActionPerformed(evt);
            }
        });

        rdIntTF.setEditable(false);
        rdIntTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("RD_Interest");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(rdIntTF))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(depositRDBt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdIntTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(depositRDBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositRDBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositRDBtActionPerformed
        // TODO add your handling code here:
           int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to Deposit RD Amount","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
         try{
             int RD_INT_FLAG=0;
            
          CustomerTransaction depositRDObject=new CustomerTransaction();
          int deposit_amount_rd=Integer.parseInt(rdTF.getText().trim());
          int newcustomerRDBal=deposit_amount_rd+temp_customer.customerRDBal;
        int  account_no=Integer.parseInt(acctnoTF.getText().trim());
        int RD_FLAG= depositRDObject.depositOrWithdraw(account_no,temp_customer.CurrentDateFTF.getText().trim(),deposit_amount_rd, newcustomerRDBal,"rd","deposit_amount","balance");
          if(!rdIntTF.getText().trim().equals("X"))
          {
              RD_INT_FLAG=depositRD_INT();
          }
          if(RD_FLAG==1 )
          { temp_customer.customerRDBal=deposit_amount_rd+temp_customer.customerRDBal;
       PreparedStatement     pstmUpdateCustomerRD=temp_customer.con.prepareStatement("update customer set rdbal=? where account_no=?");
             pstmUpdateCustomerRD.setInt(2,account_no);
             pstmUpdateCustomerRD.setInt(1,temp_customer.customerRDBal);
             pstmUpdateCustomerRD.executeUpdate();
             String msg="Amount successfully Deposited !";
             if(RD_INT_FLAG==1)
             {
               msg= "Amount  with Interest successfully Deposited !";
             }
             JOptionPane.showMessageDialog(this,""+msg,"PCCS",JOptionPane.INFORMATION_MESSAGE);
             temp_customer.updateRdBalInfo();
          }
         
               }
        catch(NumberFormatException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(this,"Transaction Failure","PCCS",JOptionPane.ERROR_MESSAGE); 
        }
        } 
    }//GEN-LAST:event_depositRDBtActionPerformed

    private void withdrawRdBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawRdBtActionPerformed
        // TODO add your handling code here:
         int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to Withdraw Amount from RD Balance","PCCS-RD Bal Withdraw",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
        if(!wrdTF.getText().trim().equals("X"))
             {
                 yrSpinner.setEnabled(false);
                         int years=(int)yrSpinner.getValue();
                 CustomerTransaction withdrawRDObject=new CustomerTransaction();
                  int RDWrAmt=Integer.parseInt(wrdTF.getText().trim());
                   int  account_no=Integer.parseInt(acctnoTF.getText().trim());
                   int newcustomerRDBal=temp_customer.customerRDBal-RDWrAmt;
         try{
             int RD_FLAG=withdrawRDObject.depositOrWithdraw(account_no,temp_customer.CurrentDateFTF.getText().trim(),RDWrAmt, newcustomerRDBal,"rd","withdraw_amount","balance");
              
             if(RD_FLAG==1 )
          { 
              temp_customer.customerRDBal=temp_customer.customerRDBal-RDWrAmt;
              temp_customer.RD_INT_YEARS=(short) (temp_customer.RD_INT_YEARS - (short)years);
               
             
          PreparedStatement  pstmUpdateCustomerRD=temp_customer.con.prepareStatement("update customer set rdbal=?,RD_INT_YEARS=? where account_no=?");
             pstmUpdateCustomerRD.setInt(3,account_no);
             pstmUpdateCustomerRD.setInt(1,temp_customer.customerRDBal);
             pstmUpdateCustomerRD.setShort(2,temp_customer.RD_INT_YEARS);
             pstmUpdateCustomerRD.executeUpdate();
             JOptionPane.showMessageDialog(this,"Transaction successful !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             temp_customer.updateRdBalInfo();
             yrSpinner.setEnabled(true);
                     
             
          }
         
        }
         
      catch(HeadlessException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Transaction Failure","PCCS",JOptionPane.ERROR_MESSAGE);
        }
             }
        else
        {
           JOptionPane.showMessageDialog(this,"You are not allowed to withdraw the money","PCCS",JOptionPane.ERROR_MESSAGE);  
        }
        }
    }//GEN-LAST:event_withdrawRdBtActionPerformed

    private void getAmtBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAmtBtActionPerformed
        // TODO add your handling code here:
       
       int  years=(int) yrSpinner.getValue();
        int withdraw_RD_amt=200*12*years;
        int Avail_RD_Bal=temp_customer.customerRDBal;
      if(withdraw_RD_amt<=Avail_RD_Bal)
       {
          wrdTF.setText(""+withdraw_RD_amt);
             withdrawRdBt.setEnabled(true);
       }
       else
       {
           wrdTF.setText("     X");
           
       }
       
    }//GEN-LAST:event_getAmtBtActionPerformed

    private void yrSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yrSpinnerStateChanged
        // TODO add your handling code here:
        withdrawRdBt.setEnabled(false);
    }//GEN-LAST:event_yrSpinnerStateChanged

    private void withdrawRDIntBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawRDIntBtActionPerformed
        // TODO add your handling code here:
          int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to Withdraw Amount from RD Interest","PCCS-RD Interest Withdraw",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
            try{
                
            int RDINTWrAmt=Integer.parseInt(wiamtTF.getText().trim());
            if(RDINTWrAmt>0)
            {
                int Avail_RD_INT_Bal=temp_customer.customerIntRDBal;
            if(RDINTWrAmt<=Avail_RD_INT_Bal)
             {
                 CustomerTransaction withdrawRDObject=new CustomerTransaction();
                 
                   int  account_no=Integer.parseInt(acctnoTF.getText().trim());
                    int newcustomerRdIntBal=temp_customer.customerIntRDBal-RDINTWrAmt;  
             int RD_INT_FLAG=withdrawRDObject.depositOrWithdraw(account_no,temp_customer.CurrentDateFTF.getText().trim(),RDINTWrAmt, newcustomerRdIntBal,"rd_interest","withdraw_interest","total_interest"); 
               if(RD_INT_FLAG==1 )
          { 
             temp_customer.customerIntRDBal=temp_customer.customerIntRDBal-RDINTWrAmt;
          PreparedStatement  pstmUpdateCustomerRD=temp_customer.con.prepareStatement("update customer set rd_interest=? where account_no=?");
             pstmUpdateCustomerRD.setInt(2,account_no);
            pstmUpdateCustomerRD.setInt(1,temp_customer.customerIntRDBal);
             pstmUpdateCustomerRD.executeUpdate();
             JOptionPane.showMessageDialog(this,"Transaction successful !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             temp_customer.updateRdBalInfo();
             }
         
        }
             else
        {
           JOptionPane.showMessageDialog(this,"You are not allowed to withdraw the money","PCCS",JOptionPane.ERROR_MESSAGE);  
        }
            } 
            else
            {
                         JOptionPane.showMessageDialog(this,"Invalid Amount !","PCCS",JOptionPane.ERROR_MESSAGE);  
  
            }
            }
      catch(HeadlessException | NumberFormatException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Transaction Failure","PCCS-Error",JOptionPane.ERROR_MESSAGE);
        }
             
       
        }
      
    }//GEN-LAST:event_withdrawRDIntBtActionPerformed

    private void getIntAmtBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getIntAmtBtActionPerformed
        // TODO add your handling code here:
         int  years=(int) yrintsp.getValue();
     int RD_INT_Wdr=calculateRDInterest(years);
         int Avail_RD_INT_Bal=temp_customer.customerIntRDBal;
       if(RD_INT_Wdr<=Avail_RD_INT_Bal)
       {
            
            wiamtTF.setText(""+RD_INT_Wdr); 
              
       }
       else
       {
          
           wiamtTF.setText("     X");
       }
       
    }//GEN-LAST:event_getIntAmtBtActionPerformed

 public int calculateRDInterest(int years)
 {
  int interest=0;
  int YearInterest=91;
    try {
        YearInterest=temp_customer.getYearlyInt();
       }
    catch (SQLException ex) {
               } 
     for(int i=1;i<=years;i++)
        {
         interest=interest+(((((i-1)*200*12)+interest)*7)/100)+YearInterest;
     
         }
    return interest;
 }

public int depositRD_INT()throws SQLException//deposit interest
{
         CustomerTransaction depositRDObject=new CustomerTransaction();
          String getRdIntValue=rdIntTF.getText().trim();
         
         
          int deposit_amount_rdInt=Integer.parseInt(getRdIntValue);
          int newcustomerRdIntBal=deposit_amount_rdInt+temp_customer.customerIntRDBal;
           int  account_no=Integer.parseInt(acctnoTF.getText().trim());
        int RD_INT_FLAG=depositRDObject.depositOrWithdraw(account_no,temp_customer.CurrentDateFTF.getText().trim(),deposit_amount_rdInt, newcustomerRdIntBal,"rd_interest","deposit_interest","total_interest");
          if(RD_INT_FLAG==1)
          { temp_customer.customerIntRDBal=deposit_amount_rdInt+temp_customer.customerIntRDBal;
           temp_customer.RD_INT_YEARS=(short) (temp_customer.RD_INT_YEARS + 1);
        PreparedStatement    pstmUpdateCustomerRD=temp_customer.con.prepareStatement("update customer set rd_interest=?,RD_INT_YEARS=? where account_no=?");
            pstmUpdateCustomerRD.setInt(3,account_no);
            pstmUpdateCustomerRD.setInt(1,temp_customer.customerIntRDBal);
            pstmUpdateCustomerRD.setInt(2,temp_customer.RD_INT_YEARS);
            pstmUpdateCustomerRD.executeUpdate();
            
            temp_customer.updateRdBalInfo();
          }  
         
         return RD_INT_FLAG;
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField acctnoTF;
    javax.swing.JButton depositRDBt;
    private javax.swing.JButton getAmtBt;
    private javax.swing.JButton getIntAmtBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    javax.swing.JTextField nameTF;
    javax.swing.JTextField rdIntTF;
    private javax.swing.JTextField rdTF;
    private javax.swing.JTextField wiamtTF;
    private javax.swing.JButton withdrawRDIntBt;
    javax.swing.JButton withdrawRdBt;
    private javax.swing.JTextField wrdTF;
    private javax.swing.JSpinner yrSpinner;
    private javax.swing.JSpinner yrintsp;
    // End of variables declaration//GEN-END:variables
}
