/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;

import java.sql.SQLException;
import javax.swing.JOptionPane;


public class UpdateInterestDialog extends javax.swing.JDialog {

    /**
     * Creates new form UpdateInterestDialog
     * @param parent
     * @param modal
     */
    public UpdateInterestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setLocation(50,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdintTF = new javax.swing.JTextField();
        loanintTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        upadte_intBT = new javax.swing.JButton();
        typecb = new javax.swing.JComboBox();
        refreshBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Interest");
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());

        rdintTF.setEditable(false);
        rdintTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdintTF.setForeground(new java.awt.Color(153, 0, 0));
        rdintTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loanintTF.setEditable(false);
        loanintTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loanintTF.setForeground(new java.awt.Color(153, 0, 0));
        loanintTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("RD INTEREST");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("LOAN INTEREST");

        upadte_intBT.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        upadte_intBT.setText("Update");
        upadte_intBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upadte_intBTActionPerformed(evt);
            }
        });

        typecb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        typecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "RD", "LOAN" }));
        typecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecbActionPerformed(evt);
            }
        });

        refreshBt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        refreshBt.setText("Refresh");
        refreshBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rdintTF, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(loanintTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upadte_intBT, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typecb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(refreshBt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rdintTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(typecb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upadte_intBT)
                    .addComponent(loanintTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecbActionPerformed
        // TODO add your handling code here:
        if(typecb.getSelectedIndex()==1)
        {
            rdintTF.setEditable(true);
             loanintTF.setEditable(false);
        }
          if(typecb.getSelectedIndex()==2)
        {
            loanintTF.setEditable(true);
             rdintTF.setEditable(false);
        }
         if(typecb.getSelectedIndex()==0)
          {
              rdintTF.setEditable(false); 
               loanintTF.setEditable(false);
          }
    }//GEN-LAST:event_typecbActionPerformed

    private void refreshBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtActionPerformed
        // TODO add your handling code here:
        rdintTF.setText(""+LoginPage.homepage.RD_INT);
        loanintTF.setText(""+LoginPage.homepage.LOAN_INT);
        
    }//GEN-LAST:event_refreshBtActionPerformed

    private void upadte_intBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upadte_intBTActionPerformed
        // TODO add your handling code here:
       
        if(typecb.getSelectedIndex()==1)
        {  int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to update RD Interest","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
            try
            {
                short NEWRDINT=Short.parseShort(rdintTF.getText().trim());
             int FLAG= updateValues.updatePCCSValues("RI_PCCS",NEWRDINT);
           
             if(FLAG==1)
             {  
                 LoginPage.homepage.RD_INT=NEWRDINT;
                 rdintTF.setEditable(false);
                 typecb.setSelectedIndex(0);
                 JOptionPane.showMessageDialog(this,"RD Interest Updated successfully ! " ,"PCCS-Update RD Int",JOptionPane.INFORMATION_MESSAGE);  
                 
             }
             else
             {
                JOptionPane.showMessageDialog(this,"Error related to Database \"PCCS\"" ,"PCCS-Update RD Int",JOptionPane.ERROR_MESSAGE);   
             }
            
            }
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(this,"Error related to Database \"PCCS\"" ,"PCCS-Update RD Int",JOptionPane.ERROR_MESSAGE);  
            }
        }
        }
        
        //loan interest
     if(typecb.getSelectedIndex()==2)
      {
            int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(this,"Are you sure you want to update Loan Interest","PCCS-Update Loan Int",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
            try
            {
                  
                short NEWLOANINT=Short.parseShort(loanintTF.getText().trim());
             int FLAG= updateValues.updatePCCSValues("LI_PCCS",NEWLOANINT);
           
             if(FLAG==1)
             {  
                 LoginPage.homepage.LOAN_INT=NEWLOANINT;
                 loanintTF.setEditable(false);
                 typecb.setSelectedIndex(0);
                 JOptionPane.showMessageDialog(this,"Loan Interest Updated successfully ! " ,"PCCS-Update Loan Int",JOptionPane.INFORMATION_MESSAGE);  
                 
             }
             else
             {
                JOptionPane.showMessageDialog(this,"Error related to Database \"PCCS\"" ,"PCCS-Update Loan Int",JOptionPane.ERROR_MESSAGE);   
             }
        }
            
            catch(SQLException e)
            {
               JOptionPane.showMessageDialog(this,"Error related to Database \"PCCS\"" ,"PCCS-Update Loan Int",JOptionPane.ERROR_MESSAGE);  
            }
        }
        }
        
        
    }//GEN-LAST:event_upadte_intBTActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    javax.swing.JTextField loanintTF;
    javax.swing.JTextField rdintTF;
    private javax.swing.JButton refreshBt;
    private javax.swing.JComboBox typecb;
    private javax.swing.JButton upadte_intBT;
    // End of variables declaration//GEN-END:variables
}
