/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PCCS;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;


public class ViewAccount extends javax.swing.JPanel {
    Adminpage refAdminpageView;
    JFormattedTextField CurrentDateFTF;
    Connection con;
    int account_no;
    String name;//to get the name
    
   
   
    
    int customerShareBal,customerShareIntBal,customerRDBal,customerIntRDBal;//get all values from customer
    short RD_INT_YEARS;
    
   
    /**
     * Creates new form ViewAccount
     */
    public ViewAccount() {
        initComponents();
        refAdminpageView=LoginPage.homepage;
         CurrentDateFTF=refAdminpageView.TransactionDateFTF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MgRbg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerBalInfoTable = new javax.swing.JTable();
        acctnoTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        desginationTF = new javax.swing.JTextField();
        batchnoTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        shareWithdrawBt = new javax.swing.JButton();
        depositShareBt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        balRadioBt = new javax.swing.JRadioButton();
        intRadioBt = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rdWithdrawBt = new javax.swing.JButton();
        depositRDBt = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(702, 337));
        setPreferredSize(new java.awt.Dimension(80, 60));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText(" Name            ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText(" Account No   ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText(" Designation  ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText(" Batch No       ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        customerBalInfoTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        customerBalInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Share", null, null, null},
                {"RD", null, null, null}
            },
            new String [] {
                "<html><body><b>Type</b><body></html>", "<html><body><b>Balance</b><body></html>", "<html><body><b>Interest</b><body></html>", "<html><body><b>Total Balance</b><body></html>"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerBalInfoTable.setAutoscrolls(false);
        customerBalInfoTable.setFocusable(false);
        customerBalInfoTable.setRowHeight(25);
        jScrollPane1.setViewportView(customerBalInfoTable);

        acctnoTF.setEditable(false);
        acctnoTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        acctnoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nameTF.setEditable(false);
        nameTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        desginationTF.setEditable(false);
        desginationTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        desginationTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        batchnoTF.setEditable(false);
        batchnoTF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batchnoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desginationTF)
                            .addComponent(batchnoTF)
                            .addComponent(nameTF)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(acctnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(desginationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(batchnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 14, -1, 310));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Share", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        shareWithdrawBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        shareWithdrawBt.setText(" Withdraw Share");
        shareWithdrawBt.setFocusable(false);
        shareWithdrawBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareWithdrawBtActionPerformed(evt);
            }
        });

        depositShareBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        depositShareBt.setText("Deposit Share");
        depositShareBt.setFocusable(false);
        depositShareBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositShareBtActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        balRadioBt.setBackground(new java.awt.Color(255, 153, 153));
        MgRbg.add(balRadioBt);
        balRadioBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        balRadioBt.setText("Balance");
        balRadioBt.setBorder(null);
        balRadioBt.setOpaque(false);
        jPanel2.add(balRadioBt);

        MgRbg.add(intRadioBt);
        intRadioBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        intRadioBt.setText("Interest");
        jPanel2.add(intRadioBt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depositShareBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shareWithdrawBt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(depositShareBt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shareWithdrawBt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 210, 160));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        rdWithdrawBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        rdWithdrawBt.setText("Withdraw RD");
        rdWithdrawBt.setFocusable(false);
        rdWithdrawBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdWithdrawBtActionPerformed(evt);
            }
        });

        depositRDBt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        depositRDBt.setText("Deposit RD");
        depositRDBt.setFocusable(false);
        depositRDBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositRDBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdWithdrawBt, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(depositRDBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositRDBt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdWithdrawBt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 181, 210, 143));
    }// </editor-fold>//GEN-END:initComponents

    private void depositShareBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositShareBtActionPerformed
        // TODO add your handling code here:
        CustomerTransaction depositShareObject=new CustomerTransaction();
       try
         {   
             if(balRadioBt.isSelected())//insert into share
             {
                  String getAmount=JOptionPane.showInputDialog(null,"Enter the share Amount","Share Deposit",JOptionPane.QUESTION_MESSAGE);
                  if(getAmount!=null)
                  {
                      String shareAmountString=getAmount.trim();
                       if(!shareAmountString.equals(""))
                       {int deposit_amount_share=Integer.parseInt(shareAmountString);
                       if(deposit_amount_share>0)
                       {
                            int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(null,"Are you sure you want to Deposit amount in share","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
                 
                 int newcustomerShareBal=deposit_amount_share+customerShareBal;//error check
             
          int Share_Flag=depositShareObject.depositOrWithdraw(account_no,CurrentDateFTF.getText().trim(),deposit_amount_share, newcustomerShareBal,"share","deposit_amount","balance");
             //Update in customer share balance
            if(Share_Flag==1)
            {
             customerShareBal=deposit_amount_share+customerShareBal;
        PreparedStatement     pstmUpdateCustomerShare=con.prepareStatement("update customer set share_bal=? where account_no=?");
             pstmUpdateCustomerShare.setInt(2,account_no);
             pstmUpdateCustomerShare.setInt(1,customerShareBal);
             pstmUpdateCustomerShare.executeUpdate();
             JOptionPane.showMessageDialog(null,"Transaction successfull !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             updateShareBalInfo();
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Error related to database","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
             }}
                       else
                       {
                           JOptionPane.showMessageDialog(null,"Invalid amount !","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE); 
                       }}
                 else
                  {
                      JOptionPane.showMessageDialog(null,"Enter the amount to be deposited","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
               }
                 
             }
             
             
            if(intRadioBt.isSelected())//insert into share interest
            {
                 String getAmount=JOptionPane.showInputDialog(null,"Enter the share Interest Amount","Share Interest Deposit",JOptionPane.QUESTION_MESSAGE);
                  if(getAmount!=null)
                  {
                      String shareInterestAmountString=getAmount.trim();
                       if(!shareInterestAmountString.equals(""))
                       { int deposit_amount_shareInt=Integer.parseInt(shareInterestAmountString);
                       if(deposit_amount_shareInt>0)
                       {
                            int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(null,"Are you sure you want to Deposit Interest in share","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
                
                int newcustomerShare_interest=deposit_amount_shareInt+customerShareIntBal;//error check
             
        int Share_INT_Flag= depositShareObject.depositOrWithdraw(account_no,CurrentDateFTF.getText(),deposit_amount_shareInt, newcustomerShare_interest,"share_interest","deposit_interest","total_interest");
             //Update in customer share balance
            if(Share_INT_Flag==1)
            {
             customerShareIntBal=deposit_amount_shareInt+customerShareIntBal;
          PreparedStatement   pstmUpdateCustomerShareInt=con.prepareStatement("update customer set share_interest=? where account_no=?");
             pstmUpdateCustomerShareInt.setInt(2,account_no);
             pstmUpdateCustomerShareInt.setInt(1,customerShareIntBal);
             pstmUpdateCustomerShareInt.executeUpdate();
             JOptionPane.showMessageDialog(null,"Transaction Successfull !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             updateShareBalInfo();
            }
               else
            {
                 JOptionPane.showMessageDialog(null,"Error related to database","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
        }}else
                  {
                      JOptionPane.showMessageDialog(null,"Invalid Amount !","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
                       }
                 else
                  {
                      JOptionPane.showMessageDialog(null,"Enter the amount to be deposited","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
           }
         }}
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
           JOptionPane.showMessageDialog(null,"Transaction Failure","PCCS ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_depositShareBtActionPerformed

    private void depositRDBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositRDBtActionPerformed
        // TODO add your handling code here:
        //check interest depoited or not
       
         RDForm rdformWindow=new RDForm(refAdminpageView, true);
         try{
             
        int CurrentYr_RD_BAL=customerRDBal-(200*12*RD_INT_YEARS);
       
        if(CurrentYr_RD_BAL==2200)//because 2400-200 understand it
        { int Yrs=(int)((customerRDBal+200)/2400);//to convert it in to 2400
            int RD_INT_DEP=((((Yrs-1)*200*12)+customerIntRDBal)*7)/100+getYearlyInt();
            
            
             rdformWindow.rdIntTF.setText(""+RD_INT_DEP);
        }
         else
        {
          rdformWindow.rdIntTF.setText("    X");
              
        }
        }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,"Error Related to Database","PCCS",JOptionPane.ERROR_MESSAGE);  
            }
       rdformWindow.withdrawRdBt.setEnabled(false); 
       rdformWindow.acctnoTF.setText(""+account_no);
       rdformWindow.nameTF.setText(name);
                
       rdformWindow.setVisible(true);
    }//GEN-LAST:event_depositRDBtActionPerformed

    public int getYearlyInt() throws SQLException
  {
           int YEAR_INTEREST;//default value
           int RD_INT=refAdminpageView.RD_INT;
           YEAR_INTEREST=((200*RD_INT)*(78))/(100*12); 
           return YEAR_INTEREST;
  }
    

    
    
    private void shareWithdrawBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareWithdrawBtActionPerformed
        // TODO add your handling code here:
       
        
        CustomerTransaction withdrawShareObject=new CustomerTransaction();
       try
         {   
             if(balRadioBt.isSelected())//insert into share
             {
                  String getAmount=JOptionPane.showInputDialog(null,"Enter the share Amount","Share Withdraw",JOptionPane.QUESTION_MESSAGE);
                  if(getAmount!=null)
                  {
                      String shareAmountString=getAmount.trim();
                       if(!shareAmountString.equals(""))
                       {
                            int withdraw_amount_share=Integer.parseInt(shareAmountString);
                            if(withdraw_amount_share>0)
                            {
                            int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(null,"Are you sure you want to Withdraw amount from share","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
            
                
                  int newcustomerShareBal=customerShareBal-withdraw_amount_share;
                   if(newcustomerShareBal>0)
                   {
            //error check
             
          int Share_Flag= withdrawShareObject.depositOrWithdraw(account_no,CurrentDateFTF.getText().trim(),withdraw_amount_share, newcustomerShareBal,"share","withdraw_amount","balance");
             //Update in customer share balance
            if(Share_Flag==1)
            {
           customerShareBal=customerShareBal-withdraw_amount_share;
        PreparedStatement     pstmUpdateCustomerShare=con.prepareStatement("update customer set share_bal=? where account_no=?");
             pstmUpdateCustomerShare.setInt(2,account_no);
             pstmUpdateCustomerShare.setInt(1,customerShareBal);
             pstmUpdateCustomerShare.executeUpdate();
             
             JOptionPane.showMessageDialog(null,"Transaction successfull !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             updateShareBalInfo();
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Error related to database","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
                   }
                   
                    else
        {
            JOptionPane.showMessageDialog(null,"Not allowed to withdraw the money","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
        }
        }
                      } else
                  {
                      JOptionPane.showMessageDialog(null,"Invalid amount !","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
                       }
                 else
                  {
                      JOptionPane.showMessageDialog(null,"Enter the amount to be deposited","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
               }
                 
             }
             
             
            if(intRadioBt.isSelected())//insert into share interest
            {
                 String getAmount=JOptionPane.showInputDialog(null,"Enter the share Interest Amount","Share Interest Withdraw",JOptionPane.QUESTION_MESSAGE);
                  if(getAmount!=null)
                  {
                      String shareInterestAmountString=getAmount.trim();
                       if(!shareInterestAmountString.equals(""))
                       {
                            int withdraw_amount_shareInt=Integer.parseInt(shareInterestAmountString);
                            if(withdraw_amount_shareInt>0)
                            {
                            int CONFIRMATION_CHECK= JOptionPane.showConfirmDialog(null,"Are you sure you want to Withdraw Interest from share","PCCS",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(CONFIRMATION_CHECK==0)
        {
                
                int newcustomerShare_interest=customerShareIntBal-withdraw_amount_shareInt;//error check
           if(newcustomerShare_interest>=0)
             {
        int Share_INT_Flag= withdrawShareObject.depositOrWithdraw(account_no,CurrentDateFTF.getText(),withdraw_amount_shareInt, newcustomerShare_interest,"share_interest","withdraw_interest","total_interest");
             //Update in customer share balance
            if(Share_INT_Flag==1)
            {
             customerShareIntBal=customerShareIntBal-withdraw_amount_shareInt;
          PreparedStatement   pstmUpdateCustomerShareInt=con.prepareStatement("update customer set share_interest=? where account_no=?");
             pstmUpdateCustomerShareInt.setInt(2,account_no);
             pstmUpdateCustomerShareInt.setInt(1,customerShareIntBal);
             pstmUpdateCustomerShareInt.executeUpdate();
             JOptionPane.showMessageDialog(null,"Transaction Successfull !","PCCS",JOptionPane.INFORMATION_MESSAGE);
             updateShareBalInfo();
            }
               else
            {
                 JOptionPane.showMessageDialog(null,"Error related to database","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
            }
        }else
           {
             JOptionPane.showMessageDialog(null,"Not allowed to withdraw the money","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);  
           }
        }
                            }
                             else
                  {
                      JOptionPane.showMessageDialog(null,"Invalid Amount !","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
                       }
                 else
                  {
                      JOptionPane.showMessageDialog(null,"Enter the amount to be deposited","PCCS ERROR",JOptionPane.INFORMATION_MESSAGE);
                  }
           }
         }}
        catch(HeadlessException | NumberFormatException | SQLException e)
        {
           JOptionPane.showMessageDialog(null,"Transaction Failure","PCCS ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_shareWithdrawBtActionPerformed

    private void rdWithdrawBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdWithdrawBtActionPerformed
     
        
         RDForm rdformWindow=new RDForm(refAdminpageView, true);
         rdformWindow.depositRDBt.setEnabled(false);
         rdformWindow.withdrawRdBt.setEnabled(false);
          rdformWindow.acctnoTF.setText(""+account_no);
          rdformWindow.nameTF.setText(name);
          rdformWindow.setVisible(true);
    
    }//GEN-LAST:event_rdWithdrawBtActionPerformed


    //get customer account information
    public void getAccountInfo() throws SQLException
     {
        account_no=refAdminpageView.account_noForView;//set the account no
        con=refAdminpageView.con;//get the connecton
     PreparedStatement   pstmViewAccount=con.prepareStatement("select name,account_no,designation,batch_no,"
                + "share_bal,share_interest,rdbal,rd_interest,"
                + "RD_INT_YEARS from customer where account_no=?");
        pstmViewAccount.setInt(1,account_no);
      ResultSet  rs=pstmViewAccount.executeQuery();
        
        if(rs.next())
         {
         nameTF.setText(rs.getString(1));//name
         name=rs.getString(1);//assign the name of customer
         acctnoTF.setText(""+rs.getInt(2));//account_no
         desginationTF.setText(rs.getString(3));
         batchnoTF.setText(rs.getString(4));
           //share
         customerShareBal=rs.getInt(5);
         customerShareIntBal=rs.getInt(6);
        //deposit
         customerRDBal=rs.getInt(7);
         customerIntRDBal=rs.getInt(8);
         RD_INT_YEARS=rs.getShort(9);
         updateShareBalInfo();
         updateRdBalInfo();
     } 
        rs.close();
        pstmViewAccount.close();
     }
    
  
    
public void updateShareBalInfo()
{
         customerBalInfoTable.setValueAt(customerShareBal, 0, 1);
         customerBalInfoTable.setValueAt(customerShareIntBal, 0, 2);
         customerBalInfoTable.setValueAt((customerShareBal+customerShareIntBal), 0, 3);
        
}
public void updateRdBalInfo()
{
         customerBalInfoTable.setValueAt(customerRDBal, 1, 1);
         customerBalInfoTable.setValueAt(customerIntRDBal, 1, 2);
         customerBalInfoTable.setValueAt((customerRDBal+customerIntRDBal), 1, 3); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MgRbg;
    private javax.swing.JTextField acctnoTF;
    private javax.swing.JRadioButton balRadioBt;
    private javax.swing.JTextField batchnoTF;
    private static javax.swing.JTable customerBalInfoTable;
    private javax.swing.JButton depositRDBt;
    private javax.swing.JButton depositShareBt;
    private javax.swing.JTextField desginationTF;
    private javax.swing.JRadioButton intRadioBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton rdWithdrawBt;
    private javax.swing.JButton shareWithdrawBt;
    // End of variables declaration//GEN-END:variables
}
