/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DBPCCS;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Statement;
public class CDB extends javax.swing.JFrame {
    /**
     * Creates new form SelectLoc
     */
    public CDB() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/6,size.height/8);     
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBt = new javax.swing.JButton();
        createDatabaseBt = new javax.swing.JButton();
        cancelBt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passTF = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cpassTF = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rdTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        liTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        efTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        miTF = new javax.swing.JTextField();
        errorInputMsgLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCCS-DB");
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());

        backBt.setText("Back");
        backBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtActionPerformed(evt);
            }
        });

        createDatabaseBt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createDatabaseBt.setText("Create Database");
        createDatabaseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatabaseBtActionPerformed(evt);
            }
        });

        cancelBt.setText("Cancel");
        cancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("UserName");
        jPanel1.add(jLabel1);

        userTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTF.setToolTipText("<=30 characters");
        jPanel1.add(userTF);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);

        passTF.setToolTipText("<=30 characters");
        jPanel1.add(passTF);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3);
        jPanel1.add(cpassTF);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2, 25, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("RD Interest");
        jPanel2.add(jLabel4);

        rdTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rdTF.setText("7");
        jPanel2.add(rdTF);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Loan Interest");
        jPanel2.add(jLabel6);

        liTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        liTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        liTF.setText("1");
        jPanel2.add(liTF);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Entry Fee");
        jPanel2.add(jLabel7);

        efTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        efTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        efTF.setText("10");
        jPanel2.add(efTF);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mice");
        jPanel2.add(jLabel5);

        miTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        miTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        miTF.setText("90");
        jPanel2.add(miTF);

        errorInputMsgLB.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backBt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createDatabaseBt)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorInputMsgLB, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorInputMsgLB, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createDatabaseBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBt)
                    .addComponent(cancelBt))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtActionPerformed
             dispose();
           Welcome.welcomePCCS.CRWin.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backBtActionPerformed

    private void createDatabaseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatabaseBtActionPerformed
    String USER,PASS,CPASS,RD_INT,LOAN_INT,MICE,ENTRY_FEE;
    USER=userTF.getText().trim();
    PASS=String.valueOf(passTF.getPassword());
    CPASS=String.valueOf(cpassTF.getPassword());
    RD_INT=rdTF.getText().trim();
    LOAN_INT=liTF.getText().trim();
    MICE=miTF.getText().trim();
    ENTRY_FEE=efTF.getText().trim();
     int FLAG_CU=1;
    if(!USER.equals("")& !PASS.equals("")& !CPASS.equals("") & !RD_INT.equals("") & !LOAN_INT.equals("")
            & !MICE.equals("") & !ENTRY_FEE.equals(""))
    {
        
        try
   {       
       setCursor(new Cursor(Cursor.WAIT_CURSOR));
        Statement stm=MPWin.con.createStatement();
        FLAG_CU=stm.executeUpdate("create user \'"+USER+"\' identified by \'"+PASS+"\'");
       
         if(PASS.equals(CPASS) & FLAG_CU==0)
        {
        stm.execute("drop user "+USER);
       DatabaseCreate.createDatabase();
       
       PreparedStatement pstPV=MPWin.con.prepareStatement("insert into pccs_values values(?,?)");
       pstPV.setString(1,"RI_PCCS");
       pstPV.setShort(2,Short.parseShort(RD_INT));
       pstPV.executeUpdate();
       pstPV.close();
       
       pstPV=MPWin.con.prepareStatement("insert into pccs_values values(?,?)");
       pstPV.setString(1,"LI_PCCS");
       pstPV.setShort(2,Short.parseShort(LOAN_INT));
       pstPV.executeUpdate();
       pstPV.close();
       
       pstPV=MPWin.con.prepareStatement("insert into pccs_values values(?,?)");
       pstPV.setString(1,"MI_PCCS");
       pstPV.setShort(2,Short.parseShort(MICE));
       pstPV.executeUpdate();
       pstPV.close();
       
       pstPV=MPWin.con.prepareStatement("insert into pccs_values values(?,?)");
       pstPV.setString(1,"EF_PCCS");
       pstPV.setShort(2,Short.parseShort(ENTRY_FEE));
       pstPV.executeUpdate();
       pstPV.close();
       
        pstPV=MPWin.con.prepareStatement("insert into pccs_ainfo values(?,?)");
       pstPV.setString(1,"USER");
       pstPV.setString(2,USER);
       pstPV.executeUpdate();
       pstPV.close();
       
        pstPV=MPWin.con.prepareStatement("insert into pccs_ainfo values(?,?)");
       pstPV.setString(1,"PASS");
       pstPV.setString(2,PASS);
       pstPV.executeUpdate();
       pstPV.close();
       FLAG_CU=stm.executeUpdate("create user \'"+USER+"\' identified by \'"+PASS+"\'");
       stm.execute("grant all on pccs.* to \'"+USER+"\'");
         stm.close();
                 JOptionPane.showMessageDialog(this,"Database Configured Sccessfully!","PCCS-DB",JOptionPane.WARNING_MESSAGE);
                System.exit(0);
        }
         else
    {
        JOptionPane.showMessageDialog(this,"Invalid Password","PCCS-DB",JOptionPane.WARNING_MESSAGE);
        passTF.setText("");
        cpassTF.setText("");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }  

   }
    catch (Exception ex) {
        if(FLAG_CU==1)
        {
             JOptionPane.showMessageDialog(this,"Invalid User","PCCS-DB",JOptionPane.WARNING_MESSAGE);
       userTF.setText("");
             passTF.setText("");
        cpassTF.setText("");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Database Already exists","PCCS-DB",JOptionPane.INFORMATION_MESSAGE);
           setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
             System.out.println(FLAG_CU);
        }
    }
       
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Fill all the Fields","PCCS-DB",JOptionPane.WARNING_MESSAGE);
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_createDatabaseBtActionPerformed

    private void cancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelBtActionPerformed
  
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBt;
    private javax.swing.JButton cancelBt;
    private javax.swing.JPasswordField cpassTF;
    private javax.swing.JButton createDatabaseBt;
    private javax.swing.JTextField efTF;
    private javax.swing.JLabel errorInputMsgLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField liTF;
    private javax.swing.JTextField miTF;
    private javax.swing.JPasswordField passTF;
    private javax.swing.JTextField rdTF;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
