/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DBPCCS;


import java.awt.Dimension;
import java.awt.Toolkit;

public class CR_DB extends javax.swing.JFrame {

  
  
    public CR_DB() {
        initComponents();
            Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/6,size.height/8);    
  
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        conDbBt = new javax.swing.JButton();
        RDbBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCCS-DB");
        setIconImage(new javax.swing.ImageIcon("PBIcon.png").getImage());

        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        conDbBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        conDbBt.setForeground(new java.awt.Color(0, 0, 153));
        conDbBt.setText("Configure Database");
        conDbBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conDbBtActionPerformed(evt);
            }
        });
        jPanel1.add(conDbBt);

        RDbBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RDbBt.setForeground(new java.awt.Color(0, 0, 153));
        RDbBt.setText("Recover Database");
        RDbBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDbBtActionPerformed(evt);
            }
        });
        jPanel1.add(RDbBt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conDbBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDbBtActionPerformed
        // TODO add your handling code here:
        CDB CDBOb=new CDB();
        CDBOb.setVisible(true);
        Welcome.welcomePCCS.CRWin.setVisible(false);
    }//GEN-LAST:event_conDbBtActionPerformed

    private void RDbBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDbBtActionPerformed
        // TODO add your handling code here:
         new RecoveryDialog(this,true).setVisible(true);
    }//GEN-LAST:event_RDbBtActionPerformed
   
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RDbBt;
    private javax.swing.JButton conDbBt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
